//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FahharTest.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNLER
    {
        public int ID { get; set; }
        public string ADI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public byte INDIRIM { get; set; }
        public Nullable<bool> ISKARGO { get; set; }
        public Nullable<decimal> SEPETFIYAT { get; set; }
        public string RESIM { get; set; }

      
    }
}
